name = "recoms-worker"
main = "src/worker.ts"
compatibility_date = "2023-06-26"

[[d1_databases]]
binding = "DB"
database_name = "dev-db-classes"
database_id = "6c175af6-e8b1-4d3b-b7ab-078be5435239"

[triggers]
crons = ["0 17 L * *"]
